### ISSUE TITLE
Jessie image doesn't load network after updating to new 'systemd'

### ISSUE THREAD

**Issue by dirtminer** [ewaldc/My-Book-Live#11]
I made the ill-advised choice to bring the Jessie image up-to-date with 'apt-get'.

As a result, 'systemd' got updated.

Once that happened, the Jessie image would no longer connect to the network.

This seems to be related to:

```
systemctl status networking
* networking.service - LSB: Raise network interfaces.
   Loaded: loaded (/etc/init.d/networking; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
```

Attempting to start the service results in other sysetmd services (systemd.login) failing.

Systemd.login seems to have an issue with "UTS Namespaces" not being compiled in the kernel, but fixing that warning doesn't seem to have restored the networking capability.

**Comment by ewaldc** [comment]
@dirtminer, it's indeed a huge risk to update the core packages in the image.

I have been able to update a number of packages including libc but it's a complex process due to dependencies and requires that you make a full backup before every upgrade. If I have / on sda2, I make a tar backup (without /dev, /run, /proc etc) on sda1 which is rather fast.
More recent versions of systemd, use the network manager and this comes with many defects and particularities, so probably good to stay away from that.

What version did you end up with?  I have systemd 215 (_systemctl --version_)

**Comment by dirtminer** [comment]
I haven't done a lot with Debian - my fatal assumption was that anything asked to upgrade was important from a security standpoint.

I went back to the original image.

After going back, I wondered if there was any way at UBOOT to switch to a seperate partition if the little button is pressed, so I won't have to open the case every time I mess this up.

**Comment by ewaldc** [comment]
There is no need to open up the case if you mess up (and believe me, I have messed up more than you can imagine).   Just read the section on uboot [here](https://github.com/ewaldc/My-Book-Live/tree/master/uboot).  You can boot from TFTP and I also created a self-recovering combination between boot.scr and the operating system.     I will investigate the use of the reset button, I know I wrote a kernel driver for it, but this I need to make uboot understand it.  I have compiled my own uboot and flashed it, but this is not something I would like support as it requires advanced hardware skills and tools.

**Comment by dirtminer** [comment]
Thanks for the pointer to the uboot 'saveenv' thing - isn't the NOR flash some low number of cycles , no wear leveling though, which makes writing bootcount each time a problem?  
Can boot.scr rename itself?

**Comment by ewaldc** [comment]
Yes, it's not like NAND flash, but my guess is that the MBL NOR flash chip will survive between 10.000 and 100000 erase cycles.  I have not been able to screw up THAT much :-).

But no doubt, the safest solution is to boot off TFTP e.g. a (OpenWRT) router.
