### ISSUE TITLE
Posted Precompiled toolchain missing files 

### ISSUE THREAD

**Issue by dirtminer** [ewaldc/My-Book-Live#12]
Attempting to duplicate kernel compilation instructions results in:
```
powerpc-openwrt-linux-gcc: error trying to exec 'cc1': execvp: No such file or director
```

Seems that it needs an additional directory:

```
lib/gcc/powerpc-openwrt-linux-musl/7.4.0/
```

**Comment by ewaldc** [comment]
@dirtminer ,
On the posted image (native MBL), I installed only gcc 4.9.  However, I have successfully installed gcc-8.3 using the posted apt sources.list (also included in latest image).  For cross compilation, you have multiple choices.
- use OpenWrt MUSL, I successfully installed from OpenWRT site linux-musl/7.4.0 (posted [here](https://github.com/ewaldc/My-Book-Live/blob/master/kernel/cross-compilation/toolchain-powerpc_464fp_gcc-7.4.0_musl.tgz)) and linux-musl/8.3.0.   I am happy to post a compressed file for Musl 8.3.0 as well
- use Debian or Ubuntu native cross compilation packages for powerpc (7.4, 8.3 and 9.2)

Hope this helps

**Comment by dirtminer** [comment]
@ewaldc 
The posted linux-musl 7.4.0 doesn't have the lib/ directory.   
That was the one I was trying to use for cross-compilation (without trying to dive head-first into the OpenWRT ecoystem).

If you can include a compressed file for Musl 8.3.0. (with the lib/  directory as well as bin) that would be awesome.

**Comment by ewaldc** [comment]
I removed linux-musl 7.4.0 and posted 8.3.0. It definitely contains /lib as a symbolic link to lib64

**Comment by ewaldc** [comment]
Please take a look at the updated readme page for cross compilation.  I have added multiple alternatives for downloading your own cross compilers..
