### ISSUE TITLE
Kernel 4.19 does not have net/tun(net/tap) interface enabled

### ISSUE THREAD

**Issue by alexbond73** [ewaldc/My-Book-Live#15]
Kernel 4.19 does not have net/tun(net/tap) interface enabled. Would it be possible to get one, with tun/tap built-in or in a module? So that openvpn client/server can be run on the wdmbl box.

**Comment by ewaldc** [comment]
My development MBL died, so I can no longer test anything.   Will see what I can do....

**Comment by ewaldc** [comment]
Can you try [this kernel](https://github.com/ewaldc/My-Book-Live/blob/master/kernel/precompiled/kernel.4.19.99_tun.tar) ?
Replace the 4.19.99 kernel _uImage_ in /boot and add _drivers/net/tun.ko_ into _/lib/modules/\<kernel version\>/kernel_

Unfortunately I can no longer test anything...

**Comment by alexbond73** [comment]
THANKS A LOT! Will try it!

**Comment by alexbond73** [comment]
It worked! The only issue - I have to load the module manually, with:
$ insmod /lib/modules/4.19.99/kernel/drivers/net/tun.ko
And I did create the node for the interface:
$ sudo mkdir /dev/net
$ sudo mknod /dev/net/tun c 10 200
$ sudo chmod 666 /dev/net/tun

**Comment by ewaldc** [comment]
Debian Jessie supports _systemd_, hence you should be able to autoload modules using [this](https://manpages.debian.org/jessie/systemd/modules-load.d.5.en.html)
