### ISSUE TITLE
kernel panic 4.9.135

### ISSUE THREAD

**Issue by trogper** [ewaldc/My-Book-Live#2]
I've had working 4.9.119_hdd_led, tried upgrading to .135
extracted tar to /root, moved uImage and dtb to /boot and modules to modules.
I have connected uart and made a log, sorry it's not complete.
[panic.log](https://github.com/ewaldc/My-Book-Live/files/2809663/panic.log)
reverting uImage and dtb back to .119 "fixed" the panic

**Comment by ewaldc** [comment]
Oops, I posted an experimental version with incorrect DMA module.  Will post a new version without DMA.

**Comment by ewaldc** [comment]
Fixed
