### ISSUE TITLE
Different version of MBL

### ISSUE THREAD

**Issue by LeandroDQuevedo** [ewaldc/My-Book-Live#22]
Hey ewaldc i would like to ask to you if you know if i use the same kernel in the WD My Book Live 02.43.10-048 : Core F/W single, i'm doing a academic project to implement a backup at this machine but i need to use a different firmware to do it. Can you help me?

**Comment by ewaldc** [comment]
@LeandroDQuevedo, with the original firmwares (Debian Lenny/Squeeze), you can only use the precompiled [kernel-2.6.32.70-ncq.tgz](https://github.com/ewaldc/My-Book-Live/blob/master/kernel/precompiled/kernel-2.6.32.70-ncq.tgz).  To run any of the 4.x or 5.x kernels, you need a more "recent" OS, like [Debian 8 (Jessie)](https://github.com/ewaldc/My-Book-Live/tree/master/debian).  Alternatively, if you want to run a truly modern OS like Debian 12 (Bookworm) , you can try [this project](https://github.com/ewaldc/mbl-debian)

**Comment by LeandroDQuevedo** [comment]
Thanks man!
