### ISSUE TITLE
while patch hunks failed

### ISSUE THREAD

**Issue by renek17** [ewaldc/My-Book-Live#3]
Hi,
I tried to compile a 4.9.149 kernel and to apply the patches. Some of them where rejected. I don't know, if this is a real issue. If it is not, please accept my apologies. The system I used is a Gentoo Base System release 2.6. Here's the output of the patching process:

#### patches/001_mbl_platform.patch ####
patching file arch/powerpc/boot/dts/apollo3g.dts
patching file arch/powerpc/configs/44x/apollo_3G_nas_defconfig
patching file arch/powerpc/platforms/44x/Kconfig
patching file arch/powerpc/platforms/44x/ppc44x_simple.c
#### patches/002_ppc4xx_ocm_enable.patch ####
patching file arch/powerpc/sysdev/ppc4xx_ocm.c
#### patches/003_enable_leds.patch ####
patching file drivers/leds/Makefile
patching file drivers/leds/Kconfig
patching file drivers/leds/leds.h
patching file arch/powerpc/platforms/44x/apollo3g-gpio.c
patching file arch/powerpc/platforms/44x/Makefile
patching file drivers/leds/led-class-3g.c
patching file drivers/leds/leds-apollo3g.c
patching file include/linux/leds.h
#### patches/004_enable_button.patch ####
patching file drivers/input/misc/a3g_button.c
patching file drivers/input/misc/Makefile
Hunk #1 succeeded at 78 (offset 6 lines).
#### patches/006_mbl_sata.patch ####
patching file drivers/ata/Kconfig
Hunk #1 succeeded at 331 (offset 1 line).
patching file drivers/ata/Makefile
Hunk #1 succeeded at 10 with fuzz 2 (offset 1 line).
patching file drivers/ata/sata_dwc_ncq.h
patching file drivers/ata/sata_dwc_ncq.c
#### patches/007_fix_64K_pages.patch ####
patching file arch/powerpc/kernel/setup-common.c
Hunk #1 succeeded at 900 (offset -11 lines).
#### patches/008_apollo3g_usb.patch ####
patching file drivers/usb/dwc_otg/Kconfig
patching file drivers/usb/dwc_otg/Makefile
patching file drivers/usb/dwc_otg/built-in.mod.c
patching file drivers/usb/dwc_otg/dwc_otg.mod.c
patching file drivers/usb/dwc_otg/dwc_otg_attr.c
patching file drivers/usb/dwc_otg/dwc_otg_attr.h
patching file drivers/usb/dwc_otg/dwc_otg_cil.c
patching file drivers/usb/dwc_otg/dwc_otg_cil.h
patching file drivers/usb/dwc_otg/dwc_otg_cil.h.bak
patching file drivers/usb/dwc_otg/dwc_otg_cil_intr.c
patching file drivers/usb/dwc_otg/dwc_otg_driver.c
patching file drivers/usb/dwc_otg/dwc_otg_driver.h
patching file drivers/usb/dwc_otg/dwc_otg_hcd.c
patching file drivers/usb/dwc_otg/dwc_otg_hcd.h
patching file drivers/usb/dwc_otg/dwc_otg_hcd_intr.c
patching file drivers/usb/dwc_otg/dwc_otg_hcd_queue.c
patching file drivers/usb/dwc_otg/dwc_otg_pcd.c
patching file drivers/usb/dwc_otg/dwc_otg_pcd.h
patching file drivers/usb/dwc_otg/dwc_otg_pcd_intr.c
patching file drivers/usb/dwc_otg/dwc_otg_plat.h
patching file drivers/usb/dwc_otg/dwc_otg_regs.h
patching file drivers/usb/dwc_otg/ppc4xx_dma.c
patching file drivers/usb/dwc_otg/ppc4xx_dma.h
patching file arch/powerpc/platforms/44x/apollo3g-usb.c
#### patches/009_ppc464_makefile.patch ####
patching file arch/powerpc/Makefile
Hunk #1 succeeded at 226 (offset 9 lines).
#### patches/200-add-meraki-mr24-ikarem-support.patch ####
patching file arch/powerpc/platforms/44x/Kconfig
Hunk #1 succeeded at 51 (offset 11 lines).
patching file arch/powerpc/platforms/44x/ppc44x_simple.c
Hunk #1 succeeded at 63 (offset 1 line).
#### patches/202-add-netgear-wndr4700-support.patch ####
patching file arch/powerpc/platforms/44x/Makefile
patching file arch/powerpc/platforms/44x/Kconfig
#### patches/203-add-meraki-mx60-buckminster-support.patch ####
patching file arch/powerpc/platforms/44x/Kconfig
Hunk #1 succeeded at 41 with fuzz 2 (offset 11 lines).
patching file arch/powerpc/platforms/44x/ppc44x_simple.c
#### patches/300-fix-atheros-nics-on-apm82181.patch ####
patching file arch/powerpc/sysdev/ppc4xx_pci.c
#### patches/301-fix-memory-map-wndr4700.patch ####
patching file arch/powerpc/sysdev/ppc4xx_pci.c
#### patches/701-powerpc_ibm_apm82181_phyclk_fix.patch ####
patching file drivers/net/ethernet/ibm/emac/core.c
Hunk #4 succeeded at 2644 (offset 18 lines).
patching file drivers/net/ethernet/ibm/emac/core.h
#### patches/702-powerpc_ibm_phy_add_dt_parser.patch ####
patching file drivers/net/ethernet/ibm/emac/core.c
Hunk #2 succeeded at 2441 (offset 18 lines).
Hunk #3 succeeded at 2734 (offset 18 lines).
Hunk #4 succeeded at 2777 (offset 18 lines).
Hunk #5 succeeded at 3246 (offset 18 lines).
patching file drivers/net/ethernet/ibm/emac/core.h
#### patches/801-usb-xhci-add-firmware-loader-for-uPD720201-and-uPD72.patch ####
patching file drivers/usb/host/xhci-pci.c
Hunk #2 succeeded at 243 (offset 20 lines).
Hunk #3 succeeded at 734 (offset 20 lines).
Hunk #4 succeeded at 807 (offset 20 lines).
#### patches/802-usb-xhci-force-msi-renesas-xhci.patch ####
patching file drivers/usb/host/xhci-pci.c
Hunk #1 succeeded at 198 with fuzz 1 (offset 10 lines).
patching file drivers/usb/host/xhci.c
Hunk #1 succeeded at 390 (offset 3 lines).
patching file drivers/usb/host/xhci.h
Hunk #1 succeeded at 1684 (offset 10 lines).
#### patches/803-crypto4xx.patch ####
patching file drivers/crypto/amcc/crypto4xx_alg.c
patching file drivers/crypto/amcc/crypto4xx_core.c
Hunk #6 succeeded at 786 (offset 2 lines).
Hunk #7 succeeded at 851 (offset 2 lines).
Hunk #8 succeeded at 863 (offset 2 lines).
Hunk #9 succeeded at 992 (offset 2 lines).
patching file drivers/crypto/amcc/crypto4xx_core.h
patching file drivers/crypto/amcc/crypto4xx_reg_def.h
patching file drivers/crypto/amcc/crypto4xx_sa.h
#### patches/804-usb-dwc2-add-amcc-usb-otg-405ex.patch ####
patching file drivers/usb/dwc2/platform.c
#### patches/901-hwmon-add-driver-for-Microchip-TC654-TC655-PWM-fan-c.patch ####
patching file drivers/hwmon/Kconfig
patching file drivers/hwmon/Makefile
patching file drivers/hwmon/tc654.c
#### patches/991-apollo3G_skbuff.patch ####
patching file net/core/skbuff.c
Hunk #1 succeeded at 1865 (offset 17 lines).
Hunk #2 succeeded at 1892 (offset 17 lines).
Hunk #3 succeeded at 1931 (offset 17 lines).
Hunk #4 succeeded at 1979 (offset 17 lines).
#### patches/992-apollo3G_emac+netconsle.patch ####
patching file drivers/net/ethernet/ibm/emac/Kconfig
patching file drivers/net/ethernet/ibm/emac/core.c
Hunk #2 FAILED at 43.
Hunk #3 succeeded at 77 (offset 1 line).
Hunk #4 FAILED at 122.
Hunk #5 succeeded at 173 (offset 10 lines).
Hunk #6 succeeded at 201 (offset 10 lines).
Hunk #7 succeeded at 240 (offset 10 lines).
Hunk #8 succeeded at 324 (offset 10 lines).
Hunk #9 succeeded at 343 (offset 10 lines).
Hunk #10 succeeded at 359 (offset 10 lines).
Hunk #11 succeeded at 391 (offset 10 lines).
Hunk #12 succeeded at 413 (offset 10 lines).
Hunk #13 succeeded at 430 (offset 10 lines).
Hunk #14 succeeded at 540 (offset 10 lines).
Hunk #15 succeeded at 554 (offset 10 lines).
Hunk #16 succeeded at 585 (offset 10 lines).
Hunk #17 succeeded at 616 (offset 10 lines).
Hunk #18 succeeded at 653 (offset 10 lines).
Hunk #19 succeeded at 666 (offset 10 lines).
Hunk #20 succeeded at 688 (offset 10 lines).
Hunk #21 succeeded at 703 (offset 10 lines).
Hunk #22 succeeded at 716 (offset 10 lines).
Hunk #23 succeeded at 751 (offset 10 lines).
Hunk #24 succeeded at 781 (offset 10 lines).
Hunk #25 succeeded at 806 (offset 10 lines).
Hunk #26 succeeded at 826 (offset 10 lines).
Hunk #27 succeeded at 868 (offset 10 lines).
Hunk #28 succeeded at 926 (offset 10 lines).
Hunk #29 succeeded at 952 (offset 10 lines).
Hunk #30 succeeded at 985 (offset 10 lines).
Hunk #31 succeeded at 1056 (offset 10 lines).
Hunk #32 succeeded at 1116 (offset 10 lines).
Hunk #33 succeeded at 1139 (offset 10 lines).
Hunk #34 succeeded at 1147 (offset 10 lines).
Hunk #35 succeeded at 1157 (offset 10 lines).
Hunk #36 succeeded at 1222 (offset 10 lines).
Hunk #37 succeeded at 1232 (offset 10 lines).
Hunk #38 succeeded at 1259 (offset 10 lines).
Hunk #39 succeeded at 1320 (offset 10 lines).
Hunk #40 succeeded at 1366 (offset 10 lines).
Hunk #41 succeeded at 1410 (offset 10 lines).
Hunk #42 succeeded at 1426 (offset 10 lines).
Hunk #43 succeeded at 1449 (offset 10 lines).
Hunk #44 succeeded at 1571 (offset 10 lines).
Hunk #45 succeeded at 1668 (offset 10 lines).
Hunk #46 succeeded at 1722 (offset 10 lines).
Hunk #47 succeeded at 1760 (offset 10 lines).
Hunk #48 succeeded at 1800 (offset 10 lines).
Hunk #49 succeeded at 1837 (offset 10 lines).
Hunk #50 succeeded at 1855 (offset 10 lines).
Hunk #51 succeeded at 1863 (offset 10 lines).
Hunk #52 succeeded at 1901 (offset 10 lines).
Hunk #53 succeeded at 1915 (offset 10 lines).
Hunk #54 succeeded at 1972 (offset 10 lines).
Hunk #55 succeeded at 1992 (offset 10 lines).
Hunk #56 succeeded at 2010 (offset 10 lines).
Hunk #57 succeeded at 2019 (offset 10 lines).
Hunk #58 succeeded at 2065 (offset 10 lines).
Hunk #59 succeeded at 2400 (offset 10 lines).
Hunk #60 succeeded at 2418 (offset 10 lines).
Hunk #61 succeeded at 2438 (offset 10 lines).
Hunk #62 succeeded at 2448 (offset 10 lines).
Hunk #63 succeeded at 2457 (offset 10 lines).
Hunk #64 FAILED at 2469.
Hunk #65 succeeded at 2733 (offset 233 lines).
Hunk #66 FAILED at 2534.
Hunk #67 succeeded at 2808 (offset 249 lines).
Hunk #68 FAILED at 2574.
Hunk #69 succeeded at 2847 (offset 250 lines).
Hunk #70 FAILED at 2610.
Hunk #71 succeeded at 2958 (offset 250 lines).
Hunk #72 succeeded at 2974 (offset 250 lines).
Hunk #73 succeeded at 2983 (offset 250 lines).
Hunk #74 succeeded at 2991 (offset 250 lines).
Hunk #75 succeeded at 3004 (offset 250 lines).
Hunk #76 succeeded at 3016 (offset 250 lines).
Hunk #77 succeeded at 3027 (offset 250 lines).
Hunk #78 succeeded at 3043 (offset 250 lines).
Hunk #79 succeeded at 3086 (offset 250 lines).
Hunk #80 succeeded at 3099 (offset 250 lines).
Hunk #81 succeeded at 3113 (offset 250 lines).
Hunk #82 succeeded at 3148 (offset 250 lines).
Hunk #83 succeeded at 3175 (offset 250 lines).
Hunk #84 succeeded at 3222 (offset 250 lines).
Hunk #85 FAILED at 3004.
Hunk #86 succeeded at 3304 (offset 256 lines).
Hunk #87 succeeded at 3332 (offset 256 lines).
Hunk #88 succeeded at 3341 (offset 256 lines).
Hunk #89 succeeded at 3364 (offset 256 lines).
Hunk #90 succeeded at 3396 (offset 256 lines).
Hunk #91 succeeded at 3407 (offset 256 lines).
7 out of 91 hunks FAILED -- saving rejects to file drivers/net/ethernet/ibm/emac/core.c.rej
patching file drivers/net/ethernet/ibm/emac/core.h
Hunk #4 succeeded at 222 with fuzz 2 (offset 4 lines).
Hunk #5 succeeded at 248 (offset 4 lines).
Hunk #6 succeeded at 274 (offset 4 lines).
Hunk #7 FAILED at 285.
Hunk #8 succeeded at 420 (offset 6 lines).
1 out of 8 hunks FAILED -- saving rejects to file drivers/net/ethernet/ibm/emac/core.h.rej
patching file drivers/net/ethernet/ibm/emac/debug.c
patching file drivers/net/ethernet/ibm/emac/emac.h
patching file drivers/net/ethernet/ibm/emac/mal.c
patching file drivers/net/ethernet/ibm/emac/mal.h
patching file drivers/net/ethernet/ibm/emac/phy.c
patching file drivers/net/ethernet/ibm/emac/phy.h
patching file drivers/net/ethernet/ibm/emac/rgmii.c
patching file drivers/net/ethernet/ibm/emac/rgmii.h
patching file drivers/net/ethernet/ibm/emac/tah.c
patching file drivers/net/ethernet/ibm/emac/tah.h

**Comment by ewaldc** [comment]
Hmm, I will need to generate a new patches/992-apollo3G_emac+netconsole.patch.  The challenge is to have one patch for all 4.9 versions, while preparing changes for 4.19.  The only files that have not been patched correctly are `drivers/net/ethernet/ibm/emac/core.[ch]`.  I posted a 7z zip of what the patched files should look like and will create a new patch file today. Thanks for posting your experience and sorry for the inconvenience.

**Comment by ewaldc** [comment]
New 992-apollo3G_emac+netconsole.patch posted and tested.
