### ISSUE TITLE
kernel compilation fails because of sata_dwc_ncq.o

### ISSUE THREAD

**Issue by renek17** [ewaldc/My-Book-Live#4]
I'm still trying to compile 4.9.149-Kernel, but it fails when compiling sata_dwc_ncq.o

  CC      drivers/ata/sata_dwc_ncq.o
In file included from drivers/ata/sata_dwc_ncq.c:22:0:
drivers/ata/sata_dwc_ncq.h:685:3: error: expected identifier or ‘(’ before ‘--’ token
 */--- /dev/null 2017-06-21 20:25:20.252000000 +0000
   ^~
drivers/ata/sata_dwc_ncq.c: In function ‘dma_isr’:
drivers/ata/sata_dwc_ncq.c:63:34: error: ‘dwc_dev_list’ undeclared (first use in this function); did you mean ‘dwc_dev_dbg’?
  struct sata_dwc_device *hsdev = dwc_dev_list[chan];
                                  ^~~~~~~~~~~~
                                  dwc_dev_dbg
drivers/ata/sata_dwc_ncq.c:63:34: note: each undeclared identifier is reported only once for each function it appears in
drivers/ata/sata_dwc_ncq.c: In function ‘sata_dwc_probe’:
drivers/ata/sata_dwc_ncq.c:1529:2: error: ‘dwc_dev_list’ undeclared (first use in this function); did you mean ‘dwc_dev_dbg’?
  dwc_dev_list[hsdev->dma_channel] = hsdev; // Initialize global dev list
  ^~~~~~~~~~~~
  dwc_dev_dbg
make[2]: *** [scripts/Makefile.build:305: drivers/ata/sata_dwc_ncq.o] Error 1
make[1]: *** [scripts/Makefile.build:555: drivers/ata] Error 2
make: *** [Makefile:1026: drivers] Error 2

**Comment by ewaldc** [comment]
OK, will need to verify how this patch ended up being wrong.  In the meantime, just use these two [files](https://github.com/ewaldc/My-Book-Live/blob/master/kernel/patches/4.9/sata_dwc_ncq.7z)

**Comment by renek17** [comment]
Now this one working. Thanks for your great work and enthusiasm.
Unfortunately now it stops at drivers/net/ethernet/ibm/emac/core.c with really much more output, i put in a txt-file at bottom.

In file included from ./include/linux/printk.h:5:0,
                 from ./include/linux/kernel.h:13,
                 from ./include/linux/list.h:8,
                 from ./include/linux/module.h:9,
                 from drivers/net/ethernet/ibm/emac/core.c:27:
./include/linux/init.h:170:20: error: redefinition of ‘__initcall_emac_init6’
  static initcall_t __initcall_##fn##id __used \
                    ^
./include/linux/init.h:200:30: note: in expansion of macro ‘__define_initcall’
 #define device_initcall(fn)  __define_initcall(fn, 6)
                              ^~~~~~~~~~~~~~~~~
./include/linux/init.h:205:24: note: in expansion of macro ‘device_initcall’
 #define __initcall(fn) device_initcall(fn)
                        ^~~~~~~~~~~~~~~
./include/linux/module.h:86:24: note: in expansion of macro ‘__initcall’
 #define module_init(x) __initcall(x);
                        ^~~~~~~~~~
drivers/net/ethernet/ibm/emac/core.c:6753:1: note: in expansion of macro ‘module_init’
 module_init(emac_init);
 ^~~~~~~~~~~
./include/linux/init.h:170:20: note: previous definition of ‘__initcall_emac_init6’ was here
  static initcall_t __initcall_##fn##id __used \
                    ^
./include/linux/init.h:200:30: note: in expansion of macro ‘__define_initcall’
 #define device_initcall(fn)  __define_initcall(fn, 6)
                              ^~~~~~~~~~~~~~~~~
./include/linux/init.h:205:24: note: in expansion of macro ‘device_initcall’
 #define __initcall(fn) device_initcall(fn)
                        ^~~~~~~~~~~~~~~
./include/linux/module.h:86:24: note: in expansion of macro ‘__initcall’
 #define module_init(x) __initcall(x);
                        ^~~~~~~~~~
drivers/net/ethernet/ibm/emac/core.c:3354:1: note: in expansion of macro ‘module_init’
 module_init(emac_init);
 ^~~~~~~~~~~
./include/linux/init.h:208:20: error: redefinition of ‘__exitcall_emac_exit’
  static exitcall_t __exitcall_##fn __exit_call = fn
                    ^
./include/linux/module.h:98:24: note: in expansion of macro ‘__exitcall’
 #define module_exit(x) __exitcall(x);
                        ^~~~~~~~~~
drivers/net/ethernet/ibm/emac/core.c:6754:1: note: in expansion of macro ‘module_exit’
 module_exit(emac_exit);
 ^~~~~~~~~~~
./include/linux/init.h:208:20: note: previous definition of ‘__exitcall_emac_exit’ was here
  static exitcall_t __exitcall_##fn __exit_call = fn
                    ^
./include/linux/module.h:98:24: note: in expansion of macro ‘__exitcall’
 #define module_exit(x) __exitcall(x);
                        ^~~~~~~~~~
drivers/net/ethernet/ibm/emac/core.c:3355:1: note: in expansion of macro ‘module_exit’
 module_exit(emac_exit);
 ^~~~~~~~~~~
drivers/net/ethernet/ibm/emac/core.c:5262:20: warning: ‘emac_irq’ defined but not used [-Wunused-function]
 static irqreturn_t emac_irq(int irq, void *dev_instance)
                    ^~~~~~~~
make[5]: *** [scripts/Makefile.build:305: drivers/net/ethernet/ibm/emac/core.o] Error 1
make[4]: *** [scripts/Makefile.build:555: drivers/net/ethernet/ibm/emac] Error 2
make[3]: *** [scripts/Makefile.build:555: drivers/net/ethernet/ibm] Error 2
make[2]: *** [scripts/Makefile.build:555: drivers/net/ethernet] Error 2
make[1]: *** [scripts/Makefile.build:555: drivers/net] Error 2
make: *** [Makefile:1026: drivers] Error 2

Maybe my source is corrupted, I'm trying on tomorrow.
[errors.txt](https://github.com/ewaldc/My-Book-Live/files/2881986/errors.txt)

**Comment by ewaldc** [comment]
I found the problem.  Both core.c and core.h are somehow duplicated (the contents is there twice)

**Comment by ewaldc** [comment]
New 992-apollo3G_emac+netconsole.patch posted.
