### ISSUE TITLE
Jessie apt source is broken

### ISSUE THREAD

**Issue by ihanbing** [ewaldc/My-Book-Live#5]
Hi, Ewaldc, as debian drop the support of PowerPC for Jessie, I met the apt-get relevant problem. Can you advise how to fix this?

Very enjoy your mod debian OS for MBL. Thank you so much.

BR,
Bing

**Comment by trogper** [comment]
Hi
Can you describe what is the apt-get relevant problem?

**Comment by jlores** [comment]
Helloo

Debian Jessie now is oldstable version and the repository moved to archive.

You only need change your sources.list ("\etc\apt\sources.list") with:

deb http://archive.debian.org/debian/  jessie main contrib non-free

Best regards

**Comment by ihanbing** [comment]
Thank you guys, it works now by adding archive apt source.

**Comment by ewaldc** [comment]
I have updated the readme for Debian Jessie to include info on new/changed repositories
