### ISSUE TITLE
Error compiling kernel 4.9

### ISSUE THREAD

**Issue by jlores** [ewaldc/My-Book-Live#8]
with new kernels> 4.9.169 does not compile, error occurs:

drivers/crypto/amcc/crypto4xx_core.c:657:21: warning: dereferencing ‘void *’ pointer
  if (pd_uinfo->sa_va->sa_command_0.bf.save_iv == SA_SAVE_IV) {
                     ^
drivers/crypto/amcc/crypto4xx_core.c:657:21: error: request for member ‘sa_command_0’ in something not a structure or union
drivers/crypto/amcc/crypto4xx_core.c:658:10: error: implicit declaration of function ‘crypto_skcipher_reqtfm’ [-Werror=implicit-function-declaration]
   struct crypto_skcipher *skcipher = crypto_skcipher_reqtfm(req);
          ^
drivers/crypto/amcc/crypto4xx_core.c:658:61: error: ‘req’ undeclared (first use in this function)
   struct crypto_skcipher *skcipher = crypto_skcipher_reqtfm(req);
                                                             ^
drivers/crypto/amcc/crypto4xx_core.c:658:61: note: each undeclared identifier is reported only once for each function it appears in
drivers/crypto/amcc/crypto4xx_core.c:660:3: error: implicit declaration of function ‘crypto4xx_memcpy_from_le32’ [-Werror=implicit-function-declaration]
   crypto4xx_memcpy_from_le32((u32 *)req->iv,
   ^
drivers/crypto/amcc/crypto4xx_core.c:661:19: warning: dereferencing ‘void *’ pointer
    pd_uinfo->sr_va->save_iv,
                   ^
drivers/crypto/amcc/crypto4xx_core.c:661:19: error: request for member ‘save_iv’ in something not a structure or union
drivers/crypto/amcc/crypto4xx_core.c:662:4: error: implicit declaration of function ‘crypto_skcipher_ivsize’ [-Werror=implicit-function-declaration]
    crypto_skcipher_ivsize(skcipher));
    ^
drivers/crypto/amcc/crypto4xx_core.c: In function ‘crypto4xx_ce_interrupt_handler’:
drivers/crypto/amcc/crypto4xx_core.c:1138:18: warning: unused variable ‘dev_status’ [-Wunused-variable]
  u32 int_status, dev_status;
                  ^
drivers/crypto/amcc/crypto4xx_core.c:1138:6: warning: unused variable ‘int_status’ [-Wunused-variable]
  u32 int_status, dev_status;
      ^
drivers/crypto/amcc/crypto4xx_core.c: In function ‘crypto4xx_probe’:
drivers/crypto/amcc/crypto4xx_core.c:1261:17: warning: unused variable ‘min’ [-Wunused-variable]
  unsigned short min;
                 ^
drivers/crypto/amcc/crypto4xx_core.c:1260:15: warning: unused variable ‘pvr’ [-Wunused-variable]
  unsigned int pvr;
               ^
cc1: some warnings being treated as errors
scripts/Makefile.build:304: recipe for target 'drivers/crypto/amcc/crypto4xx_core.o' failed
make[3]: *** [drivers/crypto/amcc/crypto4xx_core.o] Error 1
scripts/Makefile.build:555: recipe for target 'drivers/crypto/amcc' failed
make[2]: *** [drivers/crypto/amcc] Error 2
scripts/Makefile.build:555: recipe for target 'drivers/crypto' failed
make[1]: *** [drivers/crypto] Error 2
Makefile:1021: recipe for target 'drivers' failed

**Comment by jlores** [comment]
When deselect crypto hardware, the error does not happen

I don't use crypto filesystem, and runs ok.

**Comment by ewald-** [comment]
I am on assignment abroad, so I can not verify anything at the moment. Will be home next week.

**Comment by ewaldc** [comment]
Back from assignment.  No issues compiling 4.9.169 related to crypto core.  Found issues with the latest emac and sata patches though...  Will post a fix today...
